# Generated by Django 5.1.6 on 2025-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_invoice_created_at_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
